services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/app
    
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/app
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf

  db:
    build: ./docker/db
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-store: